### ISSUE TITLE
Doesn't recognize base types

### ISSUE THREAD

**Issue by Jotune** [Prince781/vala-vscode#8]
I wanted to try this extension to get auto completion feature for vala and I just copied the sample code from the [elementaryOS tutorial](https://docs.elementary.io/develop/writing-apps/hello-world). It shows a few errors out of the box while there is no issues when building the code.

![image](https://user-images.githubusercontent.com/7582114/83311167-b057b000-a20e-11ea-86a4-97d573b4ead5.png)

![image](https://user-images.githubusercontent.com/7582114/83311275-04629480-a20f-11ea-8ae4-5b34e3d6fd3c.png)

**Comment by Prince781** [comment]
That's probably because this is a standalone file that doesn't belong to a project. When compiling this file on the command line, you would use a flag like `--pkg gtk+-3.0`. In order for VLS to understand what flags to pass to the compiler, you need to either have a `compile_commands.json` file in the same directory or a `meson.build` file.

**Comment by Prince781** [comment]
Have you overcome this problem now?

**Comment by Jotune** [comment]
I understand. It's not an issue with the extension then.
Thank you for teaching me.

**Comment by danielopitz** [comment]
I have the same problem. The repo I'm using is https://github.com/elementary/music, it has a `meson.build` file, nevertheless it shows errors on all core types (`The symbol $x could not be found` where $x e.g. GLib, Gtk). 

If you need more information I would be glad to provide it.

**Comment by Prince781** [comment]
@danielopitz did you try compiling from master? There may have been a recent commit in VLS that fixes your issue.

**Comment by danielopitz** [comment]
@Prince781 compiling it from master solved the problem. Thanks!

**Comment by Prince781** [comment]
Hmm...then it looks like I have to make a release soon.

**Comment by sempasha** [comment]
@Prince781, I have similar issue with [wingpanel-indicator-newtork](https://github.com/elementary/wingpanel-indicator-network). I have vala-vscode@1.0.5 extension and vala-language-server@0.48.3 installed. All of basic types are not recognized by vscode. I can't really understand what to do. Please, point the direction, I need some clue.

**Comment by Prince781** [comment]
@sempasha VLS will notify you when project configuration fails and it's not able to proceed further to add the right packages and source files. This is most likely what's happening. Check that `meson build` succeeds in the directory.

**Comment by sempasha** [comment]
@Prince781 I have next setup:

1. Elementary OS host with installed vscode and virtualbox;
2. Elementary OS guest (virtualbox machine) with all installed dependencies, which required to build vala application;
3. Directory with vala application source code at host Elementary OS shared with guest machine.

May this be the reason, why vala language server reports `The symbol `Gtk' could not be found` and so on?

**Comment by Prince781** [comment]
@sempasha you have to run `meson build` in the directory and see whether the configuration succeeds. Do you get this message in VS Code? If so, it means that meson failed, probably due to an uninstalled dependency
![Screenshot from 2022-01-16 12-13-15](https://user-images.githubusercontent.com/1341033/149670401-39baba5a-6b74-4d41-886e-2269a285a8e0.png)
.
